# fly.toml app configuration file generated for autosell-backend

app = "autosell-backend"
primary_region = "dfw"

[build]

[env]
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "python -c 'from app.database import engine; from app.models import *; Base.metadata.create_all(bind=engine)'"
